### ISSUE TITLE
Account Redesign -- Address Lists

### ISSUE THREAD

**Issue by tawaren** [ethereum/sharding#10]
I was not sure where to ask this question, so if this is the wrong channel, feel free to delete it (in that case I would appreciate a hint, what the correct channel would be)

I read the [account redesign eip](https://github.com/ethereum/sharding/blob/develop/docs/account_redesign_eip.md) and it seems a lot more streamlined than the current account representation. 

My concern is with the two added address_lists and that if all the touched accounts have to be known up front then certain contracts that have a more dynamic address model, that calls other contracts based on its current (changeable) state can get in trouble as it is now possible that between the creation of the transaction and the execution of the transaction another transaction changed the state and the current adress_lists do no longer correspond to the actual set of accessed accounts.

As accounts do no longer have a key, value store this feature has to be emulated by creating a contract per entry and choosing the init code of the contract in a way, that the contracts address can be derived from the key which makes the behaviour described above even apply for contracts that access a value in a emulated key value store where the key is dependent on the state of the contract and not just on the transactions input data.

Is a variant planned where the read and write address lists can be omitted, such that contracts with the previously described dynamic behavior become possible without the risk that multiple tries become necessary?

**Comment by vbuterin** [comment]
> My concern is with the two added address_lists and that if all the touched accounts have to be known up front then certain contracts that have a more dynamic address model, that calls other contracts based on its current (changeable) state can get in trouble as it is now possible that between the creation of the transaction and the execution of the transaction another transaction changed the state and the current adress_lists do no longer correspond to the actual set of accessed accounts.

That's correct. This is a limitation of the new design, but a necessary one. The whole reason why stateless clients, prefetching, etc can work is precisely because we know ahead of time precisely what data needs to be accessed in order to process the transaction.

The only way omitting read/write address lists would not lead to this issue is if such a transaction paid a very high gas premium, eg. all of the gas in the entire block for a single dynamic address fetch.

**Comment by tawaren** [comment]
Thanks for the Answer.
Is the plan, that the address information is discovered by executing the transaction first locally, or is the idea more to make them statically available over the ABI of a contract where possible, or a mix of them?

When thinking about the problem with failed transactions due to changing addresses, an idea came to me I like to share.
Would it be an option, to allow a third field in the transaction containing preconditions?
The precondition would be a tripple address, storage index, expected address (the two addresses could even be indexes into the address_lists). 
If a precondition is not true, the transaction will be rejected (One question is if this is a possible attack vector as the precondition check would not consume gas).  The idea behind this would be that when for the address_list entry calculation information from mutable state in contracts is required, this can be added to the precondition.
The intention is to prevent the waste of gas especially for large and gas intensive transaction that touch a lot of addresses and thus have a higher risk of failing because of a previous state change.

This would, in addition, ensure that an attacker that tries to censor another transaction by scheduling a lot of transaction, changing the state such that the other transaction fails with a high probability, will use more gas than the honest party independent of the relative gas usage between the two contender (This scenario, on the other hand, could be seen as a flaw in the contract if it is possible and thus not the network's concern)

**Comment by hwwhww** [comment]
@tawaren You can also visit the discourse forum:
http://ethereumresearch.trydiscourse.com/c/sharding
