### ISSUE TITLE
Set the suitable range in `ShardTracker.get_add_header_logs`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/sharding#102]
### What is wrong?

1. By default, `LogHandler.get_log` uses **the start of the current period if from_block** if `from_block is None`.
https://github.com/ethereum/sharding/blob/87625b6ffff41ee5f9a6dcc15b97084f9022b6cb/sharding/handler/log_handler.py#L35-L38
2. And the `from_block` is not set in `ShardTracker.get_add_header_logs`. So it will always query the logs from the start of the current period even when some periods are missed.

### How can it be fixed
Possible solutions:
* Proposal 1.
    * Tracking main chain `latest_block_number` in `ShardTracker` and using it as `from_block` in next round.
* Proposal 2.
    * Leave the value setting in higher level (Trinity node).

My first instinct is Proposal 1. But on second thought, it's tricky to handle maintain variable here. Avoiding keeping status in sharding repo APIs is a better call.

cc @NIC619

**Comment by NIC619** [comment]
I will update `ShardTracker.get_*_logs` to allow specifying `from_block` and `to_block`.
But I'm in favor of leaving them specified in a higher level.

**Comment by hwwhww** [comment]
Yes, same here!

**Comment by jannikluhn** [comment]
Even better in my opinion would be if all these functions would take a `from_log` argument and return all logs that are newer than this log. If the log does not exist anymore (because of a reorg) they would raise a `ValueError`.

Rationale: Usually we'll want to get logs multiple times per period, meaning that we get the same logs all the time which is a bit annoying. Also, we don't realize if there are reorgs and our already retrieved logs are invalidated. With the `from_log` parameter, we get only new logs and are also notified whenever there's a reorg (in which case we can try again with older logs or just issue a warning and get all logs for the current period again).

**Comment by NIC619** [comment]
Agree that `from_log` would be helpful.
But I have a few considerations:
(1) Would there be many cases where we will store logs that are not our concern, e.g., the logs whose `notary` address is not ours?
If we are interested in whether our `register_notary` has succeeded or if a header is added in current period or if there are enough votes in this period, we have `is_notary_registered`, `is_new_header_added` and `has_enough_vote` at hand.

(2) Do we want to be actively or passively aware of re-org? I don't have enough knowledge to know whether one has significant advantage over the other but currently I'm leaning toward being actively aware of re-org.
It means that before we send either `register_notary`, `add_header` or `submit_vote` transactions, we should do a re-org check. (Of course it's better to wait for enough block confirmations first but nonetheless a re-org check gives more assurance.)

I imagine the flow would be:
a. Polling for logs
b. If the log(e.g., `add_header`) is emitted or condition is met(e.g., enough votes), marks it as pending and schedule an action(e.g.,`submit_vote` or mark the header as finalized) `X` blocks(or clock ticks) from now.
c. Do a re-org check. If there's no re-org, take the action, if there is, un-mark the pending status and resume a.

**Comment by jannikluhn** [comment]
> (1) Would there be many cases where we will store logs that are not our concern, e.g., the logs whose notary address is not ours?

I don't think so, but even with `from_log` one could add additional filters. The other functions you mentioned appear kind of "risky" to use as they only check in a single period (which may even change during a request) and are not aware of reorgs. So I think fetching logs directly is safer and only marginally messier.

(2) Do we want to be actively or passively aware of re-org? I don't have enough knowledge to know whether one has significant advantage over the other but currently I'm leaning toward being actively aware of re-org.

If we do an active check before sending the `getLogs` request or a transaction, the reorg might still happen in between. So passive should be better and also easier to implement.

**Comment by hwwhww** [comment]
> (2) Do we want to be actively or passively aware of re-org? 

* For the shard validators:
    * **If** (i) we use the beacon chain as parent chain and (ii) the same validator pool for all validators (shard notaries/beacon notaries/attesters/validators/Casper validators...), then it's highly likely that every shard validators are responsible for being the full client of beacon chain. Then may we be able to use some passive method for detecting re-org.
* For a shard full client but not validator, detecting actively is indeed safer.
* For a shard light client, we can follow LES-like mechanism. I guess it's passive.

**Comment by hwwhww** [comment]
IMO for minimal sharding protocol, *at this stage*, we can just make the testing parent chain with only one block proposer so no fork. The model will be changed soooooon. 😈

**Comment by hwwhww** [comment]
Furthermore, if we want more efficiency, we can set a normal shard full client also be a light client of parent chain *inside the node* instead of only calling JSON-RPC APIs. The client maintains headers of parent chain in its local side, so it's easy to detect re-org.

**Comment by NIC619** [comment]
> I don't think so, but even with from_log one could add additional filters.

If there are cases where these filtering helps, we could definitely add them for sure!

> ... (which may even change during a request) and are not aware of reorgs. So I think fetching logs directly is safer and only marginally messier.

I think the problem of *change during a request* is inevitable. Neither does using the `from_log`+passive re-org detection way help because at the bottom what these get-logs functions do is the same - they request for logs and provider responds what it has at the moment. And anything could happen during/after the request.

**Comment by NIC619** [comment]
> The other functions you mentioned appear kind of "risky" to use as they only check in a single period

For notary registration-related logs, we can specify which period to start searching from. For header/vote counts we do search for them in a single period because we shouldn't have to care about header/vote counts `x` periods ago.

**Comment by NIC619** [comment]
> Furthermore, if we want more efficiency, we can set a normal shard full client also be a light client of parent chain inside the node instead of only calling JSON-RPC APIs. The client maintains headers of parent chain in its local side, so it's easy to detect re-org.

But unless you modify the code in fork choice rule section and add a function that push notifications to higher level application say `SMCService` whenever there's a chain re-org, you basically have the same thing as calling via JSON_RPC because they all need to poll on the current state of the chain to know if there's a re-org.

**Comment by NIC619** [comment]
So IMO the general pattern is:
1. You keep polling on certain information you need, say a new header log.
2. Once there's a new header, record the header and also the block the tx is mined.
3. Keep polling on new header.
3.a If there's a different header(which means there's a re-org) return to step 2.
3.b If there's no new header for `X` blocks. We can assume the possibility that this header will be replaced is negligible and so we can start submitting our vote.

For informations like if we have registered or if our vote is submitted, we should track the transaction hash instead.

**Comment by hwwhww** [comment]
> But unless you modify the code in fork choice rule section and add a function that push notifications to higher level application say SMCService whenever there's a chain re-org, you basically have the same thing as calling via JSON_RPC because they all need to poll on the current state of the chain to know if there's a re-org.

Right! :) 
I did imply that the passive way needs to be triggered by [higher level IPC](https://github.com/ethereum/py-evm/issues/799#issuecomment-392778077).

**Comment by hwwhww** [comment]
@NIC619 

> So IMO the general pattern is:
(1.) You keep polling on certain information you need, say a new header log.

To be clear, do you mean `add_header` log, right?

> (2.) Once there's a new header, record the header and also the block number of which the tx is mined.
(3.) Keep polling on new header.

Do you mean polling for the "next" new header or tracking the header which is recorded in step (2)?

> (3.a) If there's a different header(which means there's a re-org) return to and repeat step 2.

By this sentence, I think you're saying the recorded header?

> (3.b) If there's no new header for X blocks. We can assume the possibility that this header will be replaced is negligible and so we can start submitting our vote.

What do you mean by "no new header for X blocks."? And assume that parent chain forked?

**Comment by NIC619** [comment]
> To be clear, do you mean `add_header` log, right?

Yes. It keeps calling `get_add_header_logs` for current period.

> Do you mean polling for the "next" new header or tracking the header which is recorded in step (2)?

By "(3.) Keep polling on new header." it basically does the same thing as (1.), i.e., it keeps calling `get_add_header_logs` for current period.
So if there's no chain re-org, the header log returned will always be the same as the one we get in (2.).
But if there's a re-org, the header log returned will be different and after comparison we will know a re-org took place. Then we no longer cares about the replaced header but move on with the new header and start a new round of `X` blocks count down.

> What do you mean by "no new header for X blocks."? And assume that parent chain forked?

Sorry for my bad wording. The "new" here actually refers to the old/new comparison between the log we get in (2.) and the log we get in (3.a). Not the "new" header for this period. 
So if we get a header log in (2.) and we keep repeating (3.) for `X` blocks and all the header logs returned are the same as the one we get in (2.) then we can be confident that this header will likely not be replaced and we can stop polling for header log and start voting.

**Comment by NIC619** [comment]
>> But unless you modify the code in fork choice rule section and add a function that push notifications to higher level application say SMCService whenever there's a chain re-org, you basically have the same thing as calling via JSON_RPC because they all need to poll on the current state of the chain to know if there's a re-org.

> Right! :)
I did imply that the passive way needs to be triggered by higher level IPC.

I see.
So I feel like we don't have to worry about re-org that much if we

**Comment by hwwhww** [comment]
@NIC619 
Hmm, I think the old solution that uses `get_new_logs` and `get_canonical_chain` is more efficient?

1. Both solutions (let's call they **old** and **tracking tx_hash** here) are stateful.
2. Do you mean that in the **tracking tx_hash** solution, the client only poll for the "latest" `add_header` log? Or the client needs to poll for "every add-header txs within `X` blocks"?
    1. If it's former: when parent chain forks, the old solution enables us to roll back to the forking point easily, and then fetch the new data; the **tracking tx_hash solution** only tells us "the re-org happened", but how to locate the forking point?
    2.  If it's latter, assume the secure finality history size is `X` blocks  as what we assumed before, then we need to `polling`: 
        1. The client has to poll for `X / PERIOD_LENGTH` txs per period. -> X times per period
        2. With the **old** solution, it need the query for `sum(P(block k forks)) where 1 <=k <= X` times per parent block. -> depends on finality.
        3. I think it makes sense if `X` is the beacon chain epoch size, but the epoch size is still unclear now.
        4. The **old** solution will detect faster since it checks per block.
