### ISSUE TITLE
ETH on shards and ETH on mainnet?

### ISSUE THREAD

**Issue by pirapira** [ethereum/sharding#38]
After reading https://github.com/ethereum/sharding/blob/develop/docs/doc.md, I have two questions
* is `COLLATOR_REWARD` applied on the shard?
* Does the expression "COLLATOR_REWARD ETH" imply that shards also have `ETH`?

**Comment by hwwhww** [comment]
1. is `COLLATOR_REWARD` applied on the shard?
Yes.

2. Does the expression "COLLATOR_REWARD ETH" imply that shards also have `ETH`?
Yes.
And in Phase 2 (two-way pegging), the preliminary idea is that user can call `txToShard` function in validator manager contract to create a receipt (with **receipt ID**) to a specific shard chain user address, and then the shard chain user can create a **receipt-consuming transaction**  with the given **receipt ID** to spend this receipt. That's how can ETH be transferred to shard chain.

(TBD) In phase 1 (no main chain fork), maybe the easiest way to encourage validators to take part in is using validator manager contract to give some rewards ETH to the succeeded `addHeader` caller.

**Comment by pirapira** [comment]
Thank you.  It's much clearer to me now.
