### ISSUE TITLE
Asserts in getEligibleProposer don't seem correct

### ISSUE THREAD

**Issue by jamesray1** [ethereum/sharding#40]
```python
def getEligibleProposer(shardId: num, period: num) -> address:
    assert period >= LOOKAHEAD_PERIODS
    assert (period - LOOKAHEAD_PERIODS) * PERIOD_LENGTH < block.number
```

Shouldn't this be:
```python
assert period <= LOOKAHEAD_PERIODS
assert (LOOKAHEAD_PERIODS - period) * PERIOD_LENGTH > block.number
```

This is supported by "The function should be able to return a value for the current period or any future period up to `LOOKAHEAD_PERIODS` periods ahead."

**Comment by hwwhww** [comment]
Thank you for reviewing!

1. The input `period` in the `getEligibleProposer` actually can be **the future period** we want to know.
2. The goal is creating a time window for the caller knowing who is the eligible proposer **`LOOKAHEAD_PERIODS` periods ahead**, it implies that the eligible proposer of the current period **cannot** be sampled **before** `LOOKAHEAD_PERIODS` periods.
So I'm a validator, `current_block_number` is `25`, `current_period` is `5`, and `LOOKAHEAD_PERIODS` is `4`. Then the validator uses message call to call `getEligibleProposer` with `period = current_period + LOOKAHEAD_PERIODS = 5 + 4 = 9`.

This line is for making sure that we already have enough block.number to sample the collator of `the given future period`.
```python
assert (period - LOOKAHEAD_PERIODS) * PERIOD_LENGTH < block.number
```
```python
assert (9 - 4) * 5 < 26
```

**Comment by jamesray1** [comment]
OK, thanks for clarifying!
