### ISSUE TITLE
Clarify Fetch candidate heads in reverse sorted order

### ISSUE THREAD

**Issue by jamesray1** [ethereum/sharding#42]
This is for https://github.com/ethereum/sharding/blob/develop/docs/doc.md#fetch-candidate-heads-in-reverse-sorted-order.

~~This is just initializing the variables to the default values of their type in zero-byte representation.~~
```
unchecked_logs = []
current_checking_score = None
```
~~Maybe clarify in a comment before the function definition that unchecked_logs is added to by the `CollationAdded` log.~~

~~When reading this section my confusion was compounded when it said after the code:~~

> ~~To re-express in plain language, the idea is to scan backwards through `CollationAdded` logs (for the correct shard), and wait until you get to one where `isNewHead = True`. Return that log first, then return all more recent logs with a score equal to that log with `isNewHead = False`, in order of oldest to most recent. Then go to the previous log with `isNewHead = True` (this is guaranteed to have score 1 lower than the previous NewHead), then go to all more recent blocks after it with that score, and so forth.~~

Also the syntax for declaring `CollationAdded` could use this: https://viper.readthedocs.io/en/latest/structure-of-a-contract.html#events, whereas in the doc it has:

> There is also one log type:
> 
> -   `CollationAdded(indexed uint256 shard, bytes collationHeader, bool isNewHead, uint256 score)`

**Comment by jamesray1** [comment]
Nevermind, I think I worked it out. Initially if the values are inititialized to zero, in the first cycle of the while loop it will get the next log.

**Comment by jamesray1** [comment]
`for i in range(len(unchecked_logs)-1, -1, -1):`

What's the point of having the range stop at -1?

Say that len(unchecked_logs) = 5. This would result in using i as:

```
...unchecked_logs[4].score...
...unchecked_logs[3].score...
...unchecked_logs[2].score...
...unchecked_logs[1].score...
...unchecked_logs[0].score...
...unchecked_logs[-1].score...
```

`unchecked_logs[-1].score` would get the last item in the range, but that would have already been checked with `len(unchecked_logs)-1`.

**Comment by jamesray1** [comment]
> Return that log first, then return all more recent logs with a score equal to that log with `isNewHead = False`, in order of oldest to most recent. Then go to the previous log with `isNewHead = True` (this is guaranteed to have a score that is 1 lower than the previous NewHead), then go to all more recent blocks after it with that score, and so forth.

I can't see how this is done in the preceding code.

**Comment by mhchia** [comment]
> Say that len(unchecked_logs) = 5. This would result in using i as:
I did an experiment in python2/3. It seems correct.
```python
>>> for i in range(5 - 1, -1, -1):
...     print(i)
... 
4
3
2
1
0
```

**Comment by mhchia** [comment]
> Also the syntax for declaring CollationAdded could use this: https://viper.readthedocs.io/en/latest/structure-of-a-contract.html#events, whereas in the doc it has:

Thank you for the suggestion. We will implement it that way in vmc.

**Comment by hwwhww** [comment]
done
