### ISSUE TITLE
Where can I learn more about deepcopy?

### ISSUE THREAD

**Issue by jamesray1** [ethereum/sharding#46]
Line 268 of the doc has deepcopy:

`tx = copy.deepcopy(txpool[0])`

Is there more information about deepcopy?

**Comment by mhchia** [comment]
https://docs.python.org/3/library/copy.html
You can check out the usage of it in the python document. On my understanding, it just copy the entire object, unlike the normal assignments leaving references uncopied.

**Comment by jamesray1** [comment]
Ah whoops, I forgot to check pydocs.
