### ISSUE TITLE
Ethereum Chart "Chain Data Size Full" link in Sharding Specification is broken

### ISSUE THREAD

**Issue by ltfschoen** [ethereum/sharding#48]
[Line 163 of the Sharding Specification](https://github.com/ethereum/sharding/blame/develop/docs/doc.md#L163) is a broken link to the Ethereum Chart for "Chain Data Size Full", as it is no longer available.
Recommend mitigation measure is to just provide a link to the Ethereum Charts https://etherscan.io/charts or rephrase and provide a specific link to "ChainData Size Growth (FAST sync)" blockchain mode using the Geth Client https://etherscan.io/chart2/chaindatasizefast

**Comment by jamesray1** [comment]
Alternatively you can use an archive of the page in December. https://web.archive.org/web/20171207061941/https://etherscan.io/chart/chaindatasizefull.

**Comment by hwwhww** [comment]
The old spec is deprecated.
