### ISSUE TITLE
Update pyethereum version in setup.py

### ISSUE THREAD

**Issue by Varunram** [ethereum/sharding#59]
The current bug in the Travis setup reads `error: Setup script exited with error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed` and a suggested fix is to upgrade pyetheruem. Is there any specific reason as to why we used a specific version of pyethereum in `setup.py`? If not, I can put in a PR for this issue. Thanks!

**Comment by hwwhww** [comment]
I just merged #53 and fixed CI.

The reasons that we use the specific "commit" of pyethereum are:
1.  sharding repo also depends on Vyper specific "commit", and it requires specific pyethereum while we want to use pyethereum with Python 3.6 supports.
2. pyethereum and Vyper are in rapid development, and sometimes, it's not backward compatible. So we have to lock the dependencies in our development.

**Comment by Varunram** [comment]
Thanks!
