### ISSUE TITLE
Gitter room and license

### ISSUE THREAD

**Issue by jamesray1** [ethereum/sharding#61]
Can someone create a Gitter room and add a link to it in a badge in the readme? I would create a room myself, but it's best if someone who has access to create a repo under the Ethereum organization does it.

Also add a license for the repo and add a license badge. I suggest CC BY SA 4.0.

I've almost finished going through the MDN Javascript guide, after that I'll continue reading through this code and start building an implementation in JS.

**Comment by hwwhww** [comment]
Currently, some related public channels are:
- https://ethresear.ch/
- https://gitter.im/ethereum/research
- https://gitter.im/ethereum/casper-scaling-and-protocol-economics
- https://gitter.im/ethereum/py-evm

Regarding the license, it's up to @vbuterin.

**Comment by jamesray1** [comment]
Yes there are plenty of related public channels, but now that sharding is no longer just a research topic but there are implementations in development, I suggest having a dedicated room for it.

**Comment by jamesray1** [comment]
Regarding the license, it's important to have something sufficiently copyleft like CC BY SA 4.0 if people like myself are going to be reading this code and making adaptations in other programming languages to use as clients.

**Comment by jamesray1** [comment]
I can make a PR for the license.

**Comment by jamesray1** [comment]
This license would be appropriate: https://github.com/ethereumjs/ethereumjs-vm/blob/master/LICENSE

**Comment by jamesray1** [comment]
For the record and by comparison, Go-Ethereum uses GNU LGPLv3, Parity uses GNU GPLv3, and EthereumJS-VM uses Mozilla Public License 2.0.

**Comment by jamesray1** [comment]
Pyethereum doesn't have a license, so that would need to be changed if sharding utils are to integrate with it and the 

Py-EVM has an MIT license.


https://github.com/ethereum/go-ethereum/blob/master/COPYING

**Comment by jamesray1** [comment]
I made a PR to add a GNU LGPL v3 license: https://github.com/ethereum/pyethereum/blob/develop/LICENSE.

**Comment by hwwhww** [comment]
I'd say as we're moving to Py-EVM + apply stateless client model, we'll rewrite almost all logic except VMC contract. Py-EVM gitter channel is the public implementation channel now.

**Comment by prestonvanloon** [comment]
GNU LGPL v3 is more restrictive than MIT. Why choose this license type?

**Comment by jamesray1** [comment]
I didn't think too much about why GNU LGPL v3 would be better, but I guess I was thinking that the additional restrictions would be helpful to be more protective of users and copyright holders, e.g. it prevents manufacturers or other parties from preventing users from modifying code installed on hardware but enables them to modify it, which restricts freedom. But MIT is less of a headache to read and think about making sure you comply with it if you are using a work.

**Comment by jamesray1** [comment]
Alright, I guess if other implementations have questions about sharding, without a dedicated room for sharding in general, they'll just have to post in the Py-EVM room, or here, or talk to you (@hwwhww) or @mhchia individually on Gitter.

**Comment by vbuterin** [comment]
I'd prefer MIT. I don't think adding any kind of copyleft to this repo is a good idea; it's likely that this repo will end up getting used as a reference implementation, and copylefting would make it a lot harder for a lot of people  especially in enterprise to use it.

**Comment by jamesray1** [comment]
GNU LGPL v3 is less copyleft than MIT, I think you mean you don't think adding anymore copyright restrictions is a good idea.
