### ISSUE TITLE
Python versions around pyeth ecosystem

### ISSUE THREAD

**Issue by hwwhww** [ethereum/sharding#7]
### [viper](https://github.com/ethereum/viper)
* **ONLY** support Python 3.6 or later

### [pyethereum](https://github.com/ethereum/pyethereum)
* support Python 2.7
* latest release: [2.1.0]
    * NOT fully support Python 3.6
* related PRs/branches
  * https://github.com/ethereum/pyethereum/pull/814

### sharding
* support Python 3.6
* support Python 2.7 **except the part that using viper for contracts** 
* dependency link
	* viper -> contracts could be translate to LLL code
	* pyethereum

### [pyethapp](https://github.com/ethereum/pyethapp)
 * support Python 2.7
 * dependency link
	 * pyethereum for testing with newer code
	 * pydevp2p for testing with newer code
	 * **sharding** (test in https://github.com/hwwhww/pyethapp/blob/sharding/setup.py#L60-L62)
* related PRs/branches
  * https://github.com/ethereum/pyethapp/pull/261 -> https://github.com/ethereum/pyethapp/pull/266
  * https://github.com/ethereum/pyethapp/pull/267
  * https://github.com/hwwhww/docker-pyeth-dev/

### [pydevp2p](https://github.com/ethereum/pydevp2p)
* support Python 2.7 and 3.4 (Python 3.6 should work fine?)
* need to bump rlp version: https://github.com/ethereum/pydevp2p/pull/88

**Comment by mhchia** [comment]
I think (2) is a good option
The workaround may be precompiling the contract and putting it directly in the transaction, thus we can remove the logic using viper.
